# Shopping Dataset Cleaning & Analysis
## 1. Import Required Libraries

In [2]:
import pandas as pd

### Load Dataset
**Source**: Kaggle Shopping Dataset  
**Link**: https://www.kaggle.com/datasets/anvitkumar/shopping-dataset?resource=download  
**Description**: Combined dataset from multiple product categories including clothing, accessories, home goods, and beauty products

In [3]:
df = pd.read_csv("D:\\celebal technologies\\week1\\dataset\\Combined_dataset.csv")

## 2. Exploratory Data Analysis (EDA)
### Display first and last rows + Dataset shape and structure

In [4]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [5]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [6]:
df.shape

(1000, 24)

In [7]:
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [8]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

## 3. Data Quality Check - Identify Missing Values
### Check for null values in all columns

In [10]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

### Issue Identified: Price Mapping Inconsistency
**Problem**: `initial_price`, `discount`, and `final_price` columns are not properly aligned  
**Observation**: The relationship `final_price = initial_price - (initial_price × discount%)` is not maintained

In [11]:
df[['initial_price','discount','final_price']]

     initial_price  discount   final_price
0             3995      58.0   "₹3,995.00"
1             2899      35.0   "₹2,899.00"
2             2999      65.0   "₹2,999.00"
3             1675      52.0   "₹1,675.00"
4             2899      17.0   "₹2,899.00"
..             ...       ...           ...
995          11890      50.0  "₹11,890.00"
996           8900      45.0   "₹8,900.00"
997           7950      50.0   "₹7,950.00"
998           3295      20.0   "₹2,636.00"
999            699      31.0     "₹699.00"

[1000 rows x 3 columns]

## 4. Handle Missing Values
**Strategy**:
- **Numeric columns** (float64, int64): Fill with `0`
- **Categorical columns** (object): Fill with `"Unknown"`

In [12]:

for col in df.columns:
    if df[col].dtype in ['float64', 'int64']:
        df[col] = df[col].fillna(0)
    else:
        df[col] = df[col].fillna("Unknown")

### Verification: Confirm All Missing Values Have Been Filled
✓ Validating null value count after filling

In [13]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

## 5. Correct Price Calculation
**Formula**: `final_price = initial_price - (initial_price × discount / 100)`  
This ensures accurate pricing after discount is applied

In [14]:
df['final_price'] = ((df['initial_price']-(df['initial_price']*df['discount']/100)))

In [15]:
df[['initial_price','discount','final_price']]

     initial_price  discount  final_price
0             3995      58.0      1677.90
1             2899      35.0      1884.35
2             2999      65.0      1049.65
3             1675      52.0       804.00
4             2899      17.0      2406.17
..             ...       ...          ...
995          11890      50.0      5945.00
996           8900      45.0      4895.00
997           7950      50.0      3975.00
998           3295      20.0      2636.00
999            699      31.0       482.31

[1000 rows x 3 columns]

## 6. Data Filtering & Feature Selection - Identify Popular Products
**Filter Criteria**: Select products with `rating > 4.0`  
**Selected Columns**: product_id, title, description, rating, ratings_count, final_price, currency, category

In [16]:
PopularProduct = df[df['rating'] > 4][['product_id','title','product_description','rating','ratings_count','final_price','currency','category']]

### Display Popular Products (Rating > 4.0)

## 7. Remove Duplicate Records
**Purpose**: Eliminate duplicate rows to ensure data uniqueness and integrity

In [17]:
df = df.drop_duplicates()

## 8. Feature Engineering - Calculate Total Sales Amount
**New Feature**: `total_amount = final_price × ratings_count`  
**Purpose**: Represents the total revenue impact of each product based on its sales volume and price

In [18]:
df['total_amount'] = df['final_price'] * df['ratings_count']

In [19]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,1677.90,INR,http://assets.myntassets.com/assets/images/837...,...,Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,25168.50
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,1884.35,INR,http://assets.myntassets.com/assets/images/913...,...,Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,126251.45
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,1049.65,INR,http://assets.myntassets.com/assets/images/176...,...,Unknown,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,237220.90
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,804.00,INR,http://assets.myntassets.com/assets/images/137...,...,Unknown,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,845808.00
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2406.17,INR,http://assets.myntassets.com/assets/images/pro...,...,Unknown,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,28874.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,5945.00,INR,http://assets.myntassets.com/assets/images/136...,...,Unknown,Unknown,"[{""size"":""Onesize""}]","[""pi-13698258""]",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,65395.00
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,4895.00,INR,http://assets.myntassets.com/assets/images/168...,...,Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,107690.00
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,3975.00,INR,http://assets.myntassets.com/assets/images/170...,...,Unknown,Unknown,"[{""size"":""Onesize""}]",Unknown,Unknown,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,19875.00
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.00,INR,http://assets.myntassets.com/assets/images/192...,...,Unknown,Tru███m R███il,"[{""size"":""Onesize""}]",Unknown,Sho███o. ███-10█████████enu███████████████████...,Unknown,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,44812.00
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,482.31,INR,http://assets.myntassets.com/assets/images/186...,...,Unknown,Unknown,"[{""size"":""Medium""}]",Unknown,Unknown,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,77651.91

In [20]:
PopularProduct['total_amount'] = PopularProduct['final_price'] * PopularProduct['ratings_count']

In [21]:
PopularProduct

,product_id,title,product_description,rating,ratings_count,final_price,currency,category,total_amount
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,1884.35,INR,backpacks,126251.45
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,1049.65,INR,backpacks,237220.90
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,804.00,INR,backpacks,845808.00
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2406.17,INR,bath-robe,28874.04
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399.00,INR,bathroom-accessories,58758.00
...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,3266.50,INR,watches,3070510.00
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3235.50,INR,watches,93829.50
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,1875.00,INR,watches,279375.00
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,4895.00,INR,watches,107690.00
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,2636.00,INR,watches,44812.00

## 9. Export Cleaned Dataset
**Output**: Save the cleaned and processed dataset to CSV format

In [22]:
df.to_csv("Shopping_dataset", index=False)
PopularProduct.to_csv("PopularProducts_dataset", index=False)